import { SideNavbar } from "@/components/side-navbar";

// export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
// };

export default function DashboardLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <main className="container mx-auto pt-12 flex gap-8   ">
   <SideNavbar />
   <div className="w-full">{children}</div>
  </main>
 );
}
